services:
  privatebin:
    image: privatebin/nginx-fpm-alpine:2.0.6
    restart: unless-stopped
    ports:
      - "${KIBAN_PRIVATEBIN_PORT:-8080}:8080"
    environment:
      KIBAN_PRIVATEBIN_PORT: ${KIBAN_PRIVATEBIN_PORT:-8080}
    volumes:
      - privatebin_data:/srv/data
      - type: bind
        source: ./conf.php
        target: /srv/cfg/conf.php
        content: |
          [main]
          name = "PrivateBin"
          discussion = true
          opendiscussion = false
          password = true
          fileupload = true
          burnafterreadingselected = false
          defaultformatter = "plaintext"
          sizelimit = 10485760
          template = "bootstrap"
          notice = ""
          languageselection = false
          urlshortener = ""
          qrcode = true
          icon = "identicon"
          cspheader = "default-src 'none'; base-uri 'self'; form-action 'none'; manifest-src 'self'; connect-src * blob:; script-src 'self' 'unsafe-eval'; worker-src 'self' blob:; style-src 'self'; font-src 'self'; frame-ancestors 'none'; img-src 'self' data: blob:; media-src blob:"
          [expire]
          default = "1week"
          [expire_options]
          5min = 300
          10min = 600
          1hour = 3600
          1day = 86400
          1week = 604800
          1month = 2592000
          1year = 31536000
          never = 0
          [traffic]
          limit = 10
          header = "X_FORWARDED_FOR"
          [purge]
          limit = 300
          batchsize = 10
          [model]
          class = Filesystem
          [model_options]
          dir = PATH "data"
volumes:
  privatebin_data:
