services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus
    ports:
      - "${KIBAN_PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - prometheus_data:/prometheus
volumes:
  prometheus_data:
