services:
  immich:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - immich-uploads:/usr/src/app/upload
    environment:
      SERVICE_URL_IMMICH_2283: ${SERVICE_URL_IMMICH_2283:-http://localhost}
      UPLOAD_LOCATION: ./library
      DB_DATA_LOCATION: ./postgres
      DB_PASSWORD: ${SERVICE_PASSWORD_POSTGRES:-kiban}
      DB_USERNAME: ${SERVICE_USER_POSTGRES:-admin}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME:-immich}
      TZ: ${TZ:-Etc/UTC}
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "2283"
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - immich-model-cache:/cache
    environment:
      UPLOAD_LOCATION: ./library
      DB_DATA_LOCATION: ./postgres
      DB_PASSWORD: ${SERVICE_PASSWORD_POSTGRES:-kiban}
      DB_USERNAME: ${SERVICE_USER_POSTGRES:-admin}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME:-immich}
      TZ: ${TZ:-Etc/UTC}
    restart: unless-stopped
  redis:
    image: redis:7.4-alpine
    healthcheck:
      test:
        - CMD
        - redis-cli
        - PING
      interval: 5s
      timeout: 10s
      retries: 20
    restart: unless-stopped
  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_POSTGRES}
      POSTGRES_USER: ${SERVICE_USER_POSTGRES}
      POSTGRES_DB: ${DB_DATABASE_NAME:-immich}
      POSTGRES_INITDB_ARGS: --data-checksums
      DB_STORAGE_TYPE: ${DB_STORAGE_TYPE:-SSD}
    volumes:
      - immich-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 20s
      retries: 10
    restart: unless-stopped
volumes:
  immich-model-cache: {}
  immich-postgres-data: {}
  immich-uploads: {}
